-- IPO Tracker — full schema, ready to paste into the Supabase SQL editor.
--
-- Generated by concatenating supabase/migrations/*.sql in order.
-- Excludes ..._cron.sql, which schedules the IPO sync and needs the Edge
-- Function deployed plus project-specific settings first.
--
-- Safe to run once on a fresh project. Re-running will error on the CREATE
-- statements, which is the intended protection against a double-apply.


-- ======================================================================
-- 20260809000001_init.sql
-- ======================================================================
-- IPO Tracker â€” initial schema.
--
-- SECURITY CONTRACT FOR THIS FILE
-- Every column holding a demat credential ends in `_enc` and is TEXT holding
-- base64(nonce || ciphertext) produced on the device with XChaCha20-Poly1305.
-- There is deliberately NO plaintext credential column anywhere in this schema.
-- If a future migration adds one, that is a bug â€” the server must never be able
-- to read a password.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- profiles: one row per auth user, holds the public half of the vault crypto
-- ---------------------------------------------------------------------------
create table public.profiles (
  id                uuid primary key references auth.users(id) on delete cascade,
  display_name      text,
  -- Argon2id salt. A salt is not a secret; storing it lets a reinstall
  -- re-derive the vault key from the master passphrase alone.
  vault_salt        text,
  -- Known plaintext encrypted under the vault key, so a wrong passphrase is
  -- detected up front instead of silently producing garbage.
  vault_verifier    text,
  -- Vault key wrapped under a key derived from the printable recovery code.
  vault_recovery_blob text,
  auto_lock_minutes integer not null default 5 check (auto_lock_minutes between 0 and 1440),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on column public.profiles.vault_salt is
  'Argon2id salt (base64). Public by design; the passphrase never leaves the device.';

-- ---------------------------------------------------------------------------
-- brokers: shared reference data, readable by every signed-in user
-- ---------------------------------------------------------------------------
create table public.brokers (
  id       uuid primary key default gen_random_uuid(),
  name     text not null,
  slug     text not null unique,
  website  text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- demat_accounts: the vault. Every sensitive field is ciphertext.
-- ---------------------------------------------------------------------------
create table public.demat_accounts (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  broker_id         uuid references public.brokers(id) on delete set null,
  -- Non-secret label so the list can render without unlocking the vault.
  nickname          text not null,
  client_id_enc     text,
  dp_id_enc         text,
  bo_id_enc         text,
  username_enc      text,
  password_enc      text,
  txn_password_enc  text,
  upi_id_enc        text,
  linked_bank_enc   text,
  pan_enc           text,
  notes_enc         text,
  is_active         boolean not null default true,
  opened_on         date,
  password_changed_at timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index demat_accounts_user_idx on public.demat_accounts(user_id) where is_active;

-- ---------------------------------------------------------------------------
-- ipos: public market data, written only by the sync-ipos Edge Function or by
-- the owning user when they add one manually.
-- ---------------------------------------------------------------------------
create type public.ipo_segment as enum ('MAINBOARD', 'SME');
create type public.ipo_status  as enum ('UPCOMING', 'OPEN', 'CLOSED', 'LISTED', 'WITHDRAWN');

create table public.ipos (
  id              uuid primary key default gen_random_uuid(),
  symbol          text not null,
  company_name    text not null,
  exchange        text not null default 'NSE',
  segment         public.ipo_segment not null default 'MAINBOARD',
  status          public.ipo_status  not null default 'UPCOMING',
  open_date       date,
  close_date      date,
  allotment_date  date,
  listing_date    date,
  price_band_min  numeric(12,2),
  price_band_max  numeric(12,2),
  lot_size        integer check (lot_size > 0),
  issue_size_cr   numeric(14,2),
  listing_price   numeric(12,2),
  current_price   numeric(12,2),
  registrar       text,
  registrar_url   text,
  -- 'NSE' | 'BSE' | 'MANUAL'. NULL user_id means shared/synced data.
  source          text not null default 'MANUAL',
  created_by      uuid references auth.users(id) on delete cascade,
  last_synced_at  timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Upsert key for the sync function. Two IPOs never share symbol + open date.
create unique index ipos_symbol_open_idx on public.ipos(symbol, open_date);
create index ipos_dates_idx on public.ipos(open_date desc nulls last);

-- Symbol is written by several independent scrapers that don't agree on
-- casing/whitespace; normalizing here (rather than trusting every writer) is
-- what keeps ipos_symbol_open_idx from treating the same company as two rows.
create or replace function public.normalize_ipo_symbol()
returns trigger as $$
begin
  new.symbol := upper(trim(new.symbol));
  return new;
end;
$$ language plpgsql;

create trigger ipos_normalize_symbol
  before insert or update on public.ipos
  for each row execute function public.normalize_ipo_symbol();

-- ---------------------------------------------------------------------------
-- ipo_applications: which of my accounts applied to what
-- ---------------------------------------------------------------------------
create type public.application_category as enum
  ('RETAIL', 'SHNI', 'BHNI', 'SHAREHOLDER', 'EMPLOYEE', 'POLICYHOLDER');
create type public.application_status as enum
  ('APPLIED', 'ALLOTTED', 'PARTIAL', 'NOT_ALLOTTED', 'WITHDRAWN', 'REFUNDED');

create table public.ipo_applications (
  id                  uuid primary key default gen_random_uuid(),
  user_id             uuid not null references auth.users(id) on delete cascade,
  ipo_id              uuid not null references public.ipos(id) on delete cascade,
  demat_account_id    uuid not null references public.demat_accounts(id) on delete cascade,
  category            public.application_category not null default 'RETAIL',
  lots                integer not null check (lots > 0),
  bid_price           numeric(12,2) not null check (bid_price > 0),
  -- Denormalised so history stays correct even if the IPO's lot size is edited.
  shares_applied      integer not null check (shares_applied > 0),
  amount_blocked      numeric(14,2) not null check (amount_blocked >= 0),
  application_no      text,
  upi_ref             text,
  applied_at          timestamptz not null default now(),
  status              public.application_status not null default 'APPLIED',
  shares_allotted     integer not null default 0 check (shares_allotted >= 0),
  allotment_checked_at timestamptz,
  sell_price          numeric(12,2),
  sold_at             timestamptz,
  notes               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  -- One application per account per category per IPO â€” matches SEBI rules.
  constraint ipo_applications_unique_bid unique (ipo_id, demat_account_id, category),
  constraint shares_allotted_within_applied check (shares_allotted <= shares_applied)
);

create index ipo_applications_user_idx on public.ipo_applications(user_id);
create index ipo_applications_ipo_idx  on public.ipo_applications(ipo_id);

-- ---------------------------------------------------------------------------
-- credential_history: prior ciphertext, so a bad edit is recoverable
-- ---------------------------------------------------------------------------
create table public.credential_history (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users(id) on delete cascade,
  demat_account_id uuid not null references public.demat_accounts(id) on delete cascade,
  field            text not null,
  old_value_enc    text not null,
  changed_at       timestamptz not null default now()
);

create index credential_history_account_idx
  on public.credential_history(demat_account_id, changed_at desc);

-- ---------------------------------------------------------------------------
-- sync_log: why the IPO list is stale, surfaced in-app instead of failing quietly
-- ---------------------------------------------------------------------------
create table public.sync_log (
  id          uuid primary key default gen_random_uuid(),
  provider    text not null,
  ok          boolean not null,
  rows_upserted integer not null default 0,
  message     text,
  ran_at      timestamptz not null default now()
);

create index sync_log_ran_at_idx on public.sync_log(ran_at desc);

-- ---------------------------------------------------------------------------
-- keep updated_at honest
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_touch        before update on public.profiles
  for each row execute function public.touch_updated_at();
create trigger demat_accounts_touch  before update on public.demat_accounts
  for each row execute function public.touch_updated_at();
create trigger ipos_touch            before update on public.ipos
  for each row execute function public.touch_updated_at();
create trigger ipo_applications_touch before update on public.ipo_applications
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- create a profile row automatically on signup
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ======================================================================
-- 20260809000002_rls.sql
-- ======================================================================
-- Row Level Security.
--
-- Encryption is the primary defence for credentials; RLS is the second line and
-- the ONLY defence for non-secret data (nicknames, application amounts, P&L).
-- Every user-owned table gets RLS enabled with no permissive fallback.

alter table public.profiles           enable row level security;
alter table public.brokers            enable row level security;
alter table public.demat_accounts     enable row level security;
alter table public.ipos               enable row level security;
alter table public.ipo_applications   enable row level security;
alter table public.credential_history enable row level security;
alter table public.sync_log           enable row level security;

-- profiles: you, and only you
create policy "profiles: read own"   on public.profiles
  for select using (auth.uid() = id);
create policy "profiles: insert own" on public.profiles
  for insert with check (auth.uid() = id);
create policy "profiles: update own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

-- brokers: shared reference data. Readable by any signed-in user, written only
-- by the service role (which bypasses RLS entirely).
create policy "brokers: read all" on public.brokers
  for select to authenticated using (true);

-- demat_accounts: the vault
create policy "accounts: read own"   on public.demat_accounts
  for select using (auth.uid() = user_id);
create policy "accounts: insert own" on public.demat_accounts
  for insert with check (auth.uid() = user_id);
create policy "accounts: update own" on public.demat_accounts
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "accounts: delete own" on public.demat_accounts
  for delete using (auth.uid() = user_id);

-- ipos: synced rows (created_by is null) are public reference data. Manually
-- added rows belong to their creator.
create policy "ipos: read shared or own" on public.ipos
  for select to authenticated using (created_by is null or auth.uid() = created_by);
create policy "ipos: insert own manual"  on public.ipos
  for insert to authenticated with check (auth.uid() = created_by);
create policy "ipos: update own manual"  on public.ipos
  for update to authenticated using (auth.uid() = created_by)
                                with check (auth.uid() = created_by);
create policy "ipos: delete own manual"  on public.ipos
  for delete to authenticated using (auth.uid() = created_by);

-- ipo_applications
create policy "applications: read own"   on public.ipo_applications
  for select using (auth.uid() = user_id);
create policy "applications: insert own" on public.ipo_applications
  for insert with check (auth.uid() = user_id);
create policy "applications: update own" on public.ipo_applications
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "applications: delete own" on public.ipo_applications
  for delete using (auth.uid() = user_id);

-- credential_history: readable and writable by owner, never updatable (append-only)
create policy "history: read own"   on public.credential_history
  for select using (auth.uid() = user_id);
create policy "history: insert own" on public.credential_history
  for insert with check (auth.uid() = user_id);
create policy "history: delete own" on public.credential_history
  for delete using (auth.uid() = user_id);

-- sync_log: readable by all signed-in users so the app can show a staleness
-- banner. Written only by the Edge Function via the service role.
create policy "sync_log: read all" on public.sync_log
  for select to authenticated using (true);

-- ======================================================================
-- 20260809000003_views_and_seed.sql
-- ======================================================================
-- P&L view + broker seed data.

-- ---------------------------------------------------------------------------
-- v_application_pnl: per-application economics, computed in Postgres so the
-- dashboard is one query instead of client-side math over every row.
--
-- security_invoker = on makes the view respect the querying user's RLS
-- policies. Without it the view would run as its owner and leak other users'
-- applications â€” this flag is load-bearing, do not remove it.
-- ---------------------------------------------------------------------------
create view public.v_application_pnl
with (security_invoker = on)
as
select
  a.id,
  a.user_id,
  a.ipo_id,
  a.demat_account_id,
  a.category,
  a.status,
  a.lots,
  a.bid_price,
  a.shares_applied,
  a.amount_blocked,
  a.shares_allotted,
  a.applied_at,
  a.sell_price,
  a.sold_at,
  i.symbol,
  i.company_name,
  i.segment,
  i.open_date,
  i.close_date,
  i.allotment_date,
  i.listing_date,
  i.listing_price,
  i.current_price,
  d.nickname as account_nickname,

  -- What the allotment actually cost.
  (a.shares_allotted * a.bid_price)::numeric(14,2) as amount_invested,

  -- Money still with the registrar: blocked while the bid is live, released
  -- once the outcome is known.
  case when a.status = 'APPLIED' then a.amount_blocked else 0 end::numeric(14,2)
    as amount_currently_blocked,

  -- Realised P&L once sold; otherwise unrealised against the best price we know
  -- (live price if we have it, else the listing price).
  case
    when a.sell_price is not null
      then (a.shares_allotted * (a.sell_price - a.bid_price))
    else 0
  end::numeric(14,2) as realised_pnl,

  case
    when a.sell_price is null and a.shares_allotted > 0
      then (a.shares_allotted * (coalesce(i.current_price, i.listing_price, a.bid_price) - a.bid_price))
    else 0
  end::numeric(14,2) as unrealised_pnl

from public.ipo_applications a
join public.ipos i on i.id = a.ipo_id
join public.demat_accounts d on d.id = a.demat_account_id;

-- ---------------------------------------------------------------------------
-- Indian brokers, seeded once. Idempotent so re-running migrations is safe.
-- ---------------------------------------------------------------------------
insert into public.brokers (name, slug, website) values
  ('Zerodha',            'zerodha',      'https://zerodha.com'),
  ('Groww',              'groww',        'https://groww.in'),
  ('Upstox',             'upstox',       'https://upstox.com'),
  ('Angel One',          'angel-one',    'https://angelone.in'),
  ('ICICI Direct',       'icici-direct', 'https://icicidirect.com'),
  ('HDFC Securities',    'hdfc-sec',     'https://hdfcsec.com'),
  ('Kotak Securities',   'kotak-sec',    'https://kotaksecurities.com'),
  ('5paisa',             '5paisa',       'https://5paisa.com'),
  ('Motilal Oswal',      'motilal',      'https://motilaloswal.com'),
  ('Sharekhan',          'sharekhan',    'https://sharekhan.com'),
  ('SBI Securities',     'sbi-sec',      'https://sbisecurities.in'),
  ('Axis Direct',        'axis-direct',  'https://axisdirect.in'),
  ('Dhan',               'dhan',         'https://dhan.co'),
  ('Fyers',              'fyers',        'https://fyers.in'),
  ('Paytm Money',        'paytm-money',  'https://paytmmoney.com'),
  ('IIFL Securities',    'iifl',         'https://iiflcapital.com'),
  ('Other',              'other',        null)
on conflict (slug) do nothing;

-- ======================================================================
-- 20260810000001_ipo_gmp.sql
-- ======================================================================
-- Grey market premium history.
--
-- GMP is an unregulated, unofficial number quoted by grey-market dealers. It is
-- not exchange data, SEBI has publicly cautioned retail investors against
-- relying on it, and on thinly-traded SME issues it is manipulable. Anything
-- rendering it must say so.
--
-- It is stored as a time series, never as a column on `ipos`, for two reasons:
-- a single reading is close to meaningless (the trend before the issue closes
-- is the signal), and overwriting would destroy the only record of what the
-- market thought at the time.

create table public.ipo_gmp (
  id            uuid primary key default gen_random_uuid(),

  -- Nullable on purpose. Chittorgarh often quotes a grey market before NSE or
  -- BSE publish the issue, and a reading we cannot attach yet is still worth
  -- keeping: the backfill pass in sync-ipos re-tries these every run, so the
  -- chart is complete from day one once the IPO itself lands.
  ipo_id        uuid references public.ipos(id) on delete cascade,

  -- Provenance, and the fallback join key while ipo_id is null.
  provider      text not null default 'CHITTORGARH',
  provider_slug text not null,          -- 'qt-foods-ipo'
  company_name  text not null,          -- as the provider spells it
  open_date     date,                   -- the provider's own issue open date

  -- The reading itself. `observed_at` is the provider's "last updated" stamp,
  -- NOT our fetch time â€” two syncs can see the same reading, and that must not
  -- put two points on the chart.
  observed_at   timestamptz not null,
  gmp           numeric(12,2),          -- premium in rupees; null = no quote
  gmp_percent   numeric(6,2),           -- against `price`
  price         numeric(12,2),          -- cap price the percent is computed on
  sub_times     numeric(10,2),          -- subscription multiple, when quoted
  source_url    text,

  synced_at     timestamptz not null default now(),
  created_at    timestamptz not null default now()
);

comment on table public.ipo_gmp is
  'Append-only grey market premium readings. Unofficial data â€” display with a disclaimer.';

-- Idempotency: re-running a sync inside one provider update window is a no-op
-- rather than a duplicate point.
create unique index ipo_gmp_reading_idx
  on public.ipo_gmp (provider, provider_slug, observed_at);

-- The charting query: newest N readings for one IPO.
create index ipo_gmp_ipo_idx
  on public.ipo_gmp (ipo_id, observed_at desc);

-- The backfill query: readings still waiting for an `ipos` row.
create index ipo_gmp_unmatched_idx
  on public.ipo_gmp (open_date, provider_slug)
  where ipo_id is null;

-- No updated_at and no touch trigger: this table is append-only, like
-- credential_history.

alter table public.ipo_gmp enable row level security;

-- Same posture as brokers and sync_log: public market data, readable by any
-- signed-in user, written only by the service role (which bypasses RLS). Rows
-- only ever reference synced IPOs, which every user can already read.
create policy "gmp: read all" on public.ipo_gmp
  for select to authenticated using (true);
